# Generated by Django 5.0.6 on 2024-07-27 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizroom',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='quiz_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
