# Generated by Django 5.0.7 on 2024-07-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizroom_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizroom',
            name='time_allotted_per_question',
        ),
        migrations.AddField(
            model_name='question',
            name='time_allotted_per_question',
            field=models.IntegerField(default=30, help_text='Time allotted per question in seconds'),
            preserve_default=False,
        ),
    ]
