# Generated by Django 5.0.7 on 2024-08-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_quizroom_time_allotted_per_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=1, help_text='The order of the question in the quiz'),
            preserve_default=False,
        ),
    ]
