# Generated by Django 5.0.7 on 2024-08-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizroom',
            name='is_buzzer',
            field=models.BooleanField(default=False),
        ),
    ]
